// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  // Migrate needs a direct (non-pooled) connection: Neon's PgBouncer pooler runs
  // in transaction mode, which doesn't support the session-level advisory locks
  // Prisma Migrate relies on. Runtime queries use the pooled DATABASE_URL instead
  // (see prismaClient.js).
  datasource: {
    url: process.env["DIRECT_URL"],
  },
});
